# Generated by Django 4.0.3 on 2022-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
